(use-modules
 (chickadee)
 (chickadee scripting)
 (chickadee math vector)
 (chickadee graphics sprite)
 (chickadee graphics texture)
 (chickadee graphics font)
 (chickadee graphics blend))
(define title? #t)
(define sprite #f)
(define speed 2.0)
(define x 0.0)
(define y 0.0)
(define (load) (set! sprite (load-image "up2.png")))
(define (fib x) (letrec ((fib-iter (lambda (n f1 f2) (if (< n 1) f1 (fib-iter (- n 1) f2 (+ f1 f2)))))) (fib-iter x 0 1)))
(define (draw alpha) (if title? (draw-text "Hello! Gamer!\nstart" (vec2 (/ 480 3) (/ 480 2)) #:scale (vec2 2.0 2.0)) (draw-sprite sprite (vec2 x y) #:blend-mode blend:alpha)))
(define (update dt) (update-agenda 1)
  (if (not title?)
      (cond
       ((key-pressed? 'right) (set! x (+ x speed)))
       ((key-pressed? 'left) (set! x (- x speed)))
       ((key-pressed? 'up) (set! y (+ y speed)))
       ((key-pressed? 'down) (set! y (- y speed)))
       ((key-pressed? 'q) (abort-game)))
      
      (if (key-pressed? 'space)
	  (if title?
	      (set! title? #f)
	      #t)
	  #f)))
(define (key-press key modify repeat) (display key) (newline))
(run-game #:window-title "shooting!" #:load load #:draw draw #:update update #:update-hz 60 #:key-press key-press #:window-width 480 #:window-height 480)
